name: Build and attach on releases

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.release.tag_name }}

      # @see https://github.com/apple/swift-format/commit/fbfe1869527923dd9f9b2edac148baccfce0dce7
      # NB: sed syntax differs between MacOS and Ubuntu
      - name: Edit `VersionOptions.swift` to update the version number
        env:
          CURRENT_RELEASE: ${{ github.event.release.tag_name }}
        run: |
          find . -name 'VersionOptions.swift' -exec sed -i 's/print(".*")/print("'$CURRENT_RELEASE'")/g' {} +
          cat Sources/swift-format/VersionOptions.swift

      # Should output executable to `.build/release/swift-format`
      - name: Build
        run: swift build --disable-sandbox -c release

      # Zip the executable so it can be given a descriptive name to distinguish the MacOS and Ubuntu builds
      - name: Create archive
        id: create-plugin-archive
        run: |
          FILENAME=swift-format.${{ github.event.release.name }}.ubuntu.zip
          zip $FILENAME .build/release/swift-format
          echo "ARCHIVE_ABSOLUTE_FILEPATH=$(pwd)/$FILENAME" >> $GITHUB_OUTPUT;

      - uses: meeDamian/github-release@2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: ${{ steps.create-plugin-archive.outputs.ARCHIVE_ABSOLUTE_FILEPATH }}
          gzip: false
          allow_override: true
